import{a as b,i as d,S as w}from"./assets/vendor-2cfd16ce.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function c(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=c(t);fetch(t.href,s)}})();function S(e){const{largeImageURL:o,webformatURL:c,tags:a,likes:t,views:s,comments:r,downloads:L}=e;return`<li class="gallery-item">
          <a href="${o}">
            <img src="${c}" alt="${a}" width="360" height="200" loading ="lazy"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${t}</p>
                <p class="image-text"><span class="image-title">Views</span> ${s}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${r}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${L}</p>
            </div>
        </a>
      </li>`}function x(e){return e.map(S).join("")}function u(e){const o=x(e);i.imagesContainer.insertAdjacentHTML("beforeend",o)}async function p(e,o){const a="https://pixabay.com/api/",t={key:"43036736-59573289802154025d43bab67",q:e,lang:"en",per_page:15,page:o};return(await b.get(a,{params:t})).data}let l,n=1,f=0;const v=15,i={searchForm:document.querySelector(".js-search-form"),btnShowMore:document.querySelector(".btn-show-more"),imagesContainer:document.querySelector(".js-images-container"),loader:document.querySelector(".loader")};i.searchForm.addEventListener("submit",M);async function M(e){e.preventDefault(),l=e.target.elements.query.value.trim(),i.imagesContainer.innerHTML="",n=1,g();const o=await p(l,n);if(!P(l,o.hits)){m();return}f=Math.ceil(o.totalHits/v),u(o.hits),y(),m(),h(),e.target.reset()}i.btnShowMore.addEventListener("click",q);async function q(){n+=1,g();try{const e=await p(l,n);u(e.hits)}catch(e){console.log(e),y()}m(),h()}function P(e,o){if(e.trim()){if(o.length===0)return d.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter",timeout:3e3}),!1}else return d.show({color:"black",message:"Sorry, the input field must be filled in to start the photo search.",position:"topCenter",timeout:3e3}),!1;return!0}function C(){i.btnShowMore.classList.remove("hidden")}function $(){i.btnShowMore.classList.add("hidden")}function g(){i.loader.classList.remove("hidden")}function m(){i.loader.classList.add("hidden")}function h(){n>=f?$():C()}function y(){new w(".images a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
