import{a as w,i as u,S}from"./assets/vendor-2cfd16ce.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function c(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=c(t);fetch(t.href,s)}})();function x(e){const{largeImageURL:o,webformatURL:c,tags:a,likes:t,views:s,comments:n,downloads:b}=e;return`<li class="gallery-item">
          <a href="${o}">
            <img src="${c}" alt="${a}" width="360" height="200" loading ="lazy"/>
            <div class="text-content-box">
                <p class="image-text"><span class="image-title">Likes</span> ${t}</p>
                <p class="image-text"><span class="image-title">Views</span> ${s}</p>
                <p class="image-text"><span class="image-title">Comments</span> ${n}</p>
                <p class="image-text"><span class="image-title">Downloads</span> ${b}</p>
            </div>
        </a>
      </li>`}function v(e){return e.map(x).join("")}function f(e){const o=v(e);i.imagesContainer.insertAdjacentHTML("beforeend",o)}async function g(e,o){const a="https://pixabay.com/api/",t={key:"43036736-59573289802154025d43bab67",q:e,lang:"en",per_page:15,page:o};return(await w.get(a,{params:t})).data}let l,r=1,p=0;const M=15,i={searchForm:document.querySelector(".js-search-form"),btnShowMore:document.querySelector(".btn-show-more"),imagesContainer:document.querySelector(".js-images-container"),loader:document.querySelector(".loader")};i.searchForm.addEventListener("submit",q);async function q(e){e.preventDefault(),l=e.target.elements.query.value.trim(),i.imagesContainer.innerHTML="",r=1,h();const o=await g(l,r);if(!C(l,o.hits)){d(),m();return}p=Math.ceil(o.totalHits/M),f(o.hits),L(),d(),y(),e.target.reset()}i.btnShowMore.addEventListener("click",P);async function P(){r+=1,h();try{const e=await g(l,r);f(e.hits),await new Promise(o=>setTimeout(o,0)),L(),r>=p&&(m(),u.show({color:"green",message:"Sorry, you have reached the end of collection.",position:"topCenter",timeout:3e3}),m())}catch(e){console.log(e)}d(),y()}function C(e,o){if(e.trim()){if(o.length===0)return u.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter",timeout:3e3}),!1}else return u.show({color:"black",message:"Sorry, the input field must be filled in to start the photo search.",position:"topCenter",timeout:3e3}),!1;return!0}function $(){i.btnShowMore.classList.remove("hidden")}function m(){i.btnShowMore.classList.add("hidden")}function h(){i.loader.classList.remove("hidden")}function d(){i.loader.classList.add("hidden")}function y(){r>=p?m():$()}function L(){new S(".images a",{captionPosition:"bottom",captionDelay:250,captionsData:"alt"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
